evolve/authenticated/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "authenticated"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.signup, name='signup'),
]

evolve/evolve/urls.py
from django.contrib import admin
from django.urls import path, include
from search import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include("search.urls")),
    path('authenticated/', include("authenticated.urls")),
    path('', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

evolve/search/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "search"

urlpatterns = [
    path("index/", views.index, name="index"),
    path("upload-file/", views.upload_file, name="upload_file"),
    path('recomand/', views.recomand, name="recomand"),
    path('goto_recomand/', views.goto_recomand, name="goto_recomand"),
    path('goto_upload_file/', views.goto_upload_file, name="goto_upload_file"),
    path("contact/", views.contact, name="contact"),
    path("read_user_lecture", views.read_user_lecture, name="read_user_lecture"),
    path("calculator/", views.calculator, name="calculator"),
    path("get_my_lecture/", views.get_my_lecture, name="get_my_lecture"),
    
]

evolve/templates/ai_list.html
{% extends "base.html" %}
{% block content %}
<center>
<h1> 인공지능에 대한 추천 과목 목록은 다음과 같습니다</h1>
<div class="col-xs-12 col-sm-12">
    <div class="col-xs-6 col-lg-6">
<table class="table table-sm table-dark" style="text-align:center;">
    <thead>
        <tr>
            
            <th scope="col">과목명</th>
        </tr>
    </thead>
    <tbody>
        {% for i in ai %}
        <tr>
            <td>{{i.lecture_name}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</div>
</center>

{% endblock %}

evolve/templates/app_list.html
{% extends "base.html" %}
{% block content %}
<center>
<h1> 웹, 앱에 대한 추천 과목 목록은 다음과 같습니다</h1>
<div class="col-xs-12 col-sm-12">
    <div class="col-xs-6 col-lg-6">
<table class="table table-sm table-dark" style="text-align:center;">
    <thead>
        <tr>
            
            <th scope="col">과목명</th>
        </tr>
    </thead>
    <tbody>
        {% for i in app %}
        <tr>
            <td>{{i.lecture_name}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</div>
</center>

{% endblock %}

evolve/templates/base.html
{% load static %}




<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %} ">
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
    <script src="{% static 'index.js' %}"></script>
    <script src="{% static 'slideshow.js' %}"></script>
    <style>
        * {
            background: #dfe6e9;
        }
    </style>
    <title>{% block title %}PAB {% endblock title %}</title>
    {% block head_content %} {% endblock head_content%}

</head>



<header class="p-3 bg-dark text-white" style="height: 70px;
padding: rem;
color: white;
background: teal;
font-weight: bold;
display: flex;
justify-content: space-between;
align-items: center;">

    <a id="logo" href="{% url 'search:index' %}" style="font-size:50px;">PAB</a>
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">

    <nav class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">

        <span style="">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'authenticated:logout' %}">{{ user.username }}(로그아웃)</a>
            {% else %}
            <a class="nav-link" href="{% url 'authenticated:login' %}">Login</a>
            {% endif %}
        </span>
        <span>
            {% if not user.is_authenticated %}
            <a class="nav-link" href="{% url 'authenticated:signup' %}">Signup</a>
            {% endif %}
        </span>

        <span>
            <a href="{% url 'search:goto_upload_file' %}" class="nav-link px-2 text-white">학점계산기</a>
        </span>
        <span>
            <a href="{% url 'search:goto_recomand' %}" class="nav-link px-2 text-white">과목추천</a>
        </span>
        <a href="{% url 'search:contact' %}" class="nav-link px-2 text-white">Contact</a>
        </span>
    </nav>


</header>





<!-- 기본 템플릿 안에 삽입될 내용 Start -->

<body>
    {% block content %} {% endblock %}
</body>

evolve/templates/contact.html
{% extends "base.html" %}


{% block content %}


<body>
    <main>
        <br><br>
        <h2 style="font-size:45px; font-style:italic; text-shadow:blueviolet 1px 1px 3px;">Our Address</h2>
        <p>Chungdae-ro, Seowon-gu, Cheongju-si, Chungcheongbuk-do, 28644, Republic of Korea</p>
        <p>E8-1 Building, Chungbuk National University</p><br>
        <div>
            <p><iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1647.9043000215127!2d127.45702453440319!3d36.6267762922955!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3565298c2b8fa25f%3A0xaed1ccc87a1c3f0f!2z7Lap67aB64yA7ZWZ6rWQIOqzte2Vmeq0gA!5e0!3m2!1sko!2skr!4v1624935521443!5m2!1sko!2skr"
                    width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe></iframe></p>
        </div>
        <br><br>
        <b style="font-size:45px; font-style:italic; text-shadow:blueviolet 1px 1px 3px;">Email Address</b><br>
        <p>
            <ul>
                <li>박정현: rkwoal216@gmail.com</li>
                <li>안영후: dksdudgn00@naver.com</li>
                <li>복무창: bmc0520@naver.com</li>
            </ul>
        </p>
        <br>
        <br>
        <br>
    </main>
</body>

{% endblock %}

evolve/templates/embed_list.html
{% extends "base.html" %}
{% block content %}
<center>
<h1> 임베디드에 대한 추천 과목 목록은 다음과 같습니다</h1>

<div class="col-xs-12 col-sm-12">
    <div class="col-xs-6 col-lg-6">
<table class="table table-sm table-dark" style="text-align:center;">
    <thead>
        <tr>
            
            <th scope="col">과목명</th>
        </tr>
    </thead>
    <tbody>
        {% for i in embedded %}
        <tr>
            <td>{{i.lecture_name}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</div>
</center>

{% endblock %}

evolve/templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}

    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}

    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

evolve/templates/game_list.html
{% extends "base.html" %}
{% block content %}
<center>
<h1> 게임에 대한 추천 과목 목록은 다음과 같습니다</h1>
<div class="col-xs-12 col-sm-12">
    <div class="col-xs-6 col-lg-6">
<table class="table table-sm table-dark" style="text-align:center;">
    <thead>
        <tr>
            
            <th scope="col">과목명</th>
        </tr>
    </thead>
    <tbody>
        {% for i in game %}
        <tr>
            <td>{{i.lecture_name}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</div>
</center>

{% endblock %}

evolve/templates/login.html
{% extends "base.html" %}
{% block content %}


<div class="container my-3">
    <form method="post" action="{% url 'authenticated:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}

        <div class="mb-3">
            <label for="username">user ID</label>
            <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" id="password"
                value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">Login!</button>
    </form>
</div>

{% endblock %}

evolve/templates/my-lecture.html
{% extends 'base.html' %}
{{my_lec}}

evolve/templates/network_list.html
{% extends "base.html" %}
{% block content %}
<center>
<h1> 네트워크에 대한 추천 과목 목록은 다음과 같습니다</h1>
<div class="col-xs-12 col-sm-12">
    <div class="col-xs-6 col-lg-6">
<table class="table table-sm table-dark" style="text-align:center;">
    <thead>
        <tr>
            
            <th scope="col">과목명</th>
        </tr>
    </thead>
    <tbody>
        {% for i in network %}
        <tr>
            <td>{{i.lecture_name}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</div>
</center>
{% endblock %}

evolve/templates/recomand.html
{% extends "base.html" %}
{% block content %}
<br>

<head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    <style>
        body {
            background: #dfe6e9;
        }
    </style>
</head> <b>
    <p>Today is <u><label id='today'></label></u></p>
</b>
<br>
<div id="pi" class="alert alert-primary"></div>

<py-script>
    import datetime as dt
    pyscript.write('today', dt.date.today().strftime('%A %B %d, %Y'))

</py-script>

<body>
    <h1 style="color:blue">관심있는 분야를 선택하세요</h1>
    <br>
    <form action="{% url 'search:recomand' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="submit" value="게임" name="game">
        <input type="submit" value="앱" name="app">
        <input type="submit" value="네트워크" name="network">
        <input type="submit" value="임베디드" name="embedded">
        <input type="submit" value="인공지능" name="ai">
    </form>
</body>
{% endblock %}

evolve/templates/result-user-lecture.html
{% extends "base.html" %}
{% block content %}
<h1 style="color:blue">전공 및 교양 현황</h1>
<br>

{% for sco in sd%}
    <h2>{{sco.field}} ({{sco.my_score}} / {{sco.min_score}})</h2>
    {% for sub in sco.sub_field%}
        <h3> &nbsp;&nbsp;&nbsp;&nbsp;{{sub.sub_field}} ({{sub.my_score}} / {{sub.min_score}})</h3>
    {% endfor %}
{% endfor %}

</form>
{% endblock %}

evolve/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="wrapper" style="text-align: center;">
    <h1>회원가입</h1>
    <form method="POST">
        {% csrf_token %}
        아이디: <br>
        <input name="username" type="text">
        <br>
        비밀번호: <br>
        <input name="password1" type="password">
        <br>
        비밀번호 확인: <br>
        <input name="password2" type="password">
        <br>
        이메일: <br>
        <input name="email" type="email">
        <br><br>
        <input type="submit" class="btn btn-primary" value="Sign Up">
        <br>
        <br>
        Have you account?


        <br>

        <a class="nav-link" href="{% url 'authenticated:login' %}">Login</a>
    </form>
</div>
{% endblock %}

evolve/templates/upload-file.html
{% extends "base.html" %}
{% block content %}

<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">


<div style="margin-top: 30px;">
    <p style="color:black; font-size:30px;">계산하고자 하는 수강현황 파일을 업로드 해주세요(format: xlsx, csv)</p>
</div>

<hr>
<br>
<div class="input-group mb-3" style="display: flex; justify-content: center;">
    <form action="{% url 'search:upload_file' %}" method="POST" enctype="multipart/form-data">
        <input type="file" name="uploaded_file" style=" background:#c7ecee;; color:#c7ecee;" value="file">
        {% csrf_token %}
        <input type="submit" value="Upload" onclick="upload_file()"
            style="width:100px; height:50px; background:#686de0; color:#c7ecee;">
    </form>
    <br>
    <br>
    <br>
    <br>
</div>
<div class="input-group mb-3" style="display: flex; justify-content: center;">
    <form action="{% url 'search:calculator' %}" method="POST">
        {% csrf_token %}
        <select name="year" style="-webkit-appearance:none; -moz-appearance:none;
        appearance:none;  ">
            <option value="2019">2019</option>
            <option value="2020">2020</option>
            <option value="2021">2021</option>
            <option value="2022">2022</option>
        </select>
        <input type="text" name="file_name" class="form-control" aria-label="Text input with dropdown button"
            placeholder="파일명을 입력하세용">
        <input type="submit" name="calculator" class="form-control" aria-label="Text input with dropdown button"
            value="파일 계산!">

    </form>
</div>

<br>





<br>
<br>
{% endblock %}